<?php

namespace AppBundle\Repository;

/**
 * ArbeitsrapportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArbeitsrapportRepository extends \Doctrine\ORM\EntityRepository
{
}
