<?php

namespace AppBundle\Repository;

/**
 * KundeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KundeRepository extends \Doctrine\ORM\EntityRepository
{
}
