<?php

namespace AppBundle\Repository;

/**
 * KundenlisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KundenlisteRepository extends \Doctrine\ORM\EntityRepository
{
}
