<?php

namespace AppBundle\Repository;

/**
 * MateriallisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MateriallisteRepository extends \Doctrine\ORM\EntityRepository
{
}
