<?php

namespace AppBundle\Repository;

/**
 * MaterialeintragRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialeintragRepository extends \Doctrine\ORM\EntityRepository
{
}
