<?php

namespace AppBundle\Repository;

/**
 * MaterialeintraglisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialeintraglisteRepository extends \Doctrine\ORM\EntityRepository
{
}
