<?php

namespace AppBundle\Repository;

/**
 * MitarbeiterlisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MitarbeiterlisteRepository extends \Doctrine\ORM\EntityRepository
{
}
