<?php

namespace AppBundle\Repository;

/**
 * StundeneintragRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StundeneintragRepository extends \Doctrine\ORM\EntityRepository
{
}
