<?php

namespace AppBundle\Repository;

/**
 * StundeneintraglisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StundeneintraglisteRepository extends \Doctrine\ORM\EntityRepository
{
}
