# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    firewalls:       
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login 
                   
            logout:
                path:   /logout
                target: /login
    
    access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
    - { path: ^/kunden/new, roles: ROLE_ADMIN}
    - { path: ^/kundenliste, roles: ROLE_NO_ACCESS }
    - { path: ^/studeneintrag, roles: ROLE_NO_ACCESS }
    - { path: ^/materialliste, roles: ROLE_NO_ACCESS }
    - { path: ^/materialeintragliste, roles: ROLE_NO_ACCESS }
    - { path: ^/stundeneintragliste, roles: ROLE_NO_ACCESS }
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
    
    
         

    providers:
        in_memory:
            memory:
                users:
                    Mitarbeiter:
                        password: pass
                        roles: 'ROLE_USER'
                    Chef:
                        password: admin
                        roles: 'ROLE_ADMIN' 
    encoders:
         Symfony\Component\Security\Core\User\User: plaintext

          
   
        
    
    

